mod stable_deref_gen_clone_tests;
mod stable_deref_gen_drain_tests;
mod stable_deref_gen_map_overflow_tests;
mod stable_deref_gen_map_tests;
mod stable_deref_gen_retain_tests;
mod stable_deref_gen_snapshot_tests;
